id: I7C2CF227
legacy_id: P000540
ocr_import_info:
  bdrc_scan_id: W3CN4051
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T15:41:01'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T14:21:32.367404+00:00'
last_modified: 2022-09-03 22:21:53.255841
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN4051
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN4051
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཟབ་ཆོས་ཞི་ཁྲོ་དགོངས་པ་རང་གྲོལ་གྱི་དབུ་ཚལ་དྲི་མའི་འཇིགས་སྐྱོབ།
statistics:
  ocr_word_mean_confidence_index: 0.5691808929372937
  ocr_word_median_confidence_index: 0.5699999928474426
quality: null
bases:
  I3CN4238:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4238
      total_pages: 1066
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN4238.txt
    statistics:
      ocr_word_median_confidence_index: 0.5699999928474426
      ocr_word_mean_confidence_index: 0.5691808929372937
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
